{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "planka.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "planka.labels" . | nindent 4 }}
    app.kubernetes.io/component: planka
  finalizers:
  - kubernetes.io/pvc-protection
spec:
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  {{- end }}
  accessModes:
  {{- range .Values.persistence.accessModes }}
    - {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
{{- end }}