apiVersion: v1
kind: Secret
metadata:
  name: {{ include "planka.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "planka.labels" . | nindent 4 }}
    app.kubernetes.io/component: planka
type: Opaque
data:
  planka-secretKey: {{ .Values.planka.secretKey | default (randAlphaNum 32) | toString | b64enc | quote }}