apiVersion: v1
kind: Service
metadata:
  name: {{ include "planka.fullname" . }}
  labels:
    {{- include "planka.labels" . | nindent 4 }}
    app.kubernetes.io/component: "planka"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "planka.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: "planka"
